apiVersion: v1
kind: PersistentVolume
metadata:
  name: dapp-store
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/Users/harshil/Documents/projects/assignments/pvSpace"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dapp-store-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: manual
